version: '3.8'

services:
  
  # content streaming
  public_jellyfin:
    image: jellyfin/jellyfin:10.8.10
    container_name: public_jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_PUBLIC_PORT}:8096"
    volumes:
      - "${JELLYFIN_PUBLIC_CONTENT_MOVIES}:/movies"
      - "${JELLYFIN_PUBLIC_CONTENT_TV_SHOWS}:/tv"
      - "${DOCKER_LOC}/public_jellyfin/cache:/cache"
      - "${DOCKER_LOC}/public_jellyfin/config:/config"

  local_jellyfin:
    image: jellyfin/jellyfin:10.8.10
    container_name: local_jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_LOCAL_PORT}:8096"
    volumes:
      - "${JELLYFIN_LOCAL_CONTENT_MISC}:/misc"
      - "${DOCKER_LOC}/local_jellyfin/cache:/cache"
      - "${DOCKER_LOC}/local_jellyfin/config:/config"

  # YTDL

  ytdl:
    image: tzahi12345/youtubedl-material:latest
    container_name: ytdl
    environment:
      ytdl_mongodb_connection_string : 'mongodb://ytdl_mongo:27017'
      ytdl_use_local_db : 'false'
      write_ytdl_config: 'true'
    restart: unless-stopped
    depends_on:
      - ytdl_mongo
    ports:
      - "${PORT_YTDL}:17442"
    volumes:
      - "${DOCKER_LOC}/ytdl/appdata:/app/appdata"
      - "${DOCKER_LOC}/ytdl/subscriptions:/app/subscriptions"
      - "${DOCKER_LOC}/ytdl/users:/app/users"
      - "${YTDL_CONTENT}/audio:/app/audio"
      - "${YTDL_CONTENT}/video:/app/video"

  # mongodb for yt downloader - not exposed
  ytdl_mongo:
    image: mongo:4
    container_name: ytdl_mongo
    restart: unless-stopped
    volumes:
      - "${DOCKER_LOC}/ytdl_mongo:/data/db"
